services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'ailohq/apollo-subgraph-publish']
    volumes:
      - ".:/plugin:ro"
